# FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-python:3-build

FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-python:3-build

# RUN pip install RPi.GPIO spidev serial

RUN install_packages libnfc-bin libnfc-dev libnfc-examples libnfc6

WORKDIR /usr/src

COPY examples/ ./examples/

CMD [ "/bin/bash" ]
