FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-python:3-build

# RUN install_packages libnfc-bin libnfc-dev libnfc-examples libnfc6 
RUN install_packages nodejs npm

RUN pip install RPi.GPIO spidev serial

WORKDIR /usr/app

COPY ./ ./

# RUN ["cat","libnfc.conf.addition",">> /etc/nfc/libnfc.conf"]

RUN npm install

CMD ["/bin/bash"]

# CMD [ "npm", "start" ]
