FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-python:3-build

RUN curl -sL https://deb.nodesource.com/setup_16.x | sudo bash -

RUN apt-get install -y nodejs

RUN pip install RPi.GPIO spidev serial

WORKDIR /usr/app

COPY ./ ./

RUN npm install

CMD [ "npm", "start" ]
